export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DOWNLOAD_TIMEOUT: "DOWNLOAD_TIMEOUT",
  DOWNLOAD_CANCELLED: "DOWNLOAD_CANCELLED",
  NO_RESPONSE_BODY: "NO_RESPONSE_BODY",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  NO_FORMAT_SELECTED: "NO_FORMAT_SELECTED",
  RATE_LIMIT_HIT: "RATE_LIMIT_HIT",
  UNEXPECTED_SERVER_ERROR: "UNEXPECTED_SERVER_ERROR",
  DIALOG_CANCELLED: "DIALOG_CANCELLED",
  DIALOG_FAILED: "DIALOG_FAILED",
  PLATFORM_NOT_SUPPORTED: "PLATFORM_NOT_SUPPORTED",
  COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
