/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamDownloadRouteImport } from './routes/api/stream-download'
import { Route as PlaygroundTimerIndexRouteImport } from './routes/playground/timer/index'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamDownloadRoute = ApiStreamDownloadRouteImport.update({
  id: '/api/stream-download',
  path: '/api/stream-download',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundTimerIndexRoute = PlaygroundTimerIndexRouteImport.update({
  id: '/playground/timer/',
  path: '/playground/timer/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/stream-download': typeof ApiStreamDownloadRoute
  '/playground/timer': typeof PlaygroundTimerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/stream-download': typeof ApiStreamDownloadRoute
  '/playground/timer': typeof PlaygroundTimerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/stream-download': typeof ApiStreamDownloadRoute
  '/playground/timer/': typeof PlaygroundTimerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/stream-download' | '/playground/timer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/api/stream-download' | '/playground/timer'
  id: '__root__' | '/' | '/$' | '/api/stream-download' | '/playground/timer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiStreamDownloadRoute: typeof ApiStreamDownloadRoute
  PlaygroundTimerIndexRoute: typeof PlaygroundTimerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-download': {
      id: '/api/stream-download'
      path: '/api/stream-download'
      fullPath: '/api/stream-download'
      preLoaderRoute: typeof ApiStreamDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/timer/': {
      id: '/playground/timer/'
      path: '/playground/timer'
      fullPath: '/playground/timer'
      preLoaderRoute: typeof PlaygroundTimerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiStreamDownloadRoute: ApiStreamDownloadRoute,
  PlaygroundTimerIndexRoute: PlaygroundTimerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
